# Site settings

title: meagan's site
email: meagan@meaganwaller.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
collections:
  posts:
    output: true
    permalink: /:slug
  pages:
    output: true
    permalink: /:slug

plugins:
  - jekyll-archives
  - jekyll-last-modified-at
  - jekyll-sitemap
  - jekyll-target-blank
  - jekyll-tailwindcss
  - jekyll-tidy

markdown: kramdown
highlighter: rouge
include:
  - "_pages"
